# 1교시 숙제

## 1. 행렬 정렬

In [9]:
import numpy as np
a = np.array([[2,1,6],[0,7,4],[5,3,2]]) 
a

array([[2, 1, 6],
       [0, 7, 4],
       [5, 3, 2]])

In [10]:
np.sort(a,axis=0)

array([[0, 1, 2],
       [2, 3, 4],
       [5, 7, 6]])

## 2. 행렬 쌓기

In [24]:
a = np.array([0,1,2,3,4,5])
np.vstack([a,a+10,a+20,a+30,a+40,a+50])

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [19]:
a = np.arange(6)
b = np.array([[0],[10],[20],[30],[40],[50]])
a+b

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [33]:
a = np.arange(60).reshape(6,-1)[:,:6]
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

### 2-1. 홀수만 고르면?

In [29]:
a[a%2==1]

array([ 1,  3,  5, 11, 13, 15, 21, 23, 25, 31, 33, 35, 41, 43, 45, 51, 53,
       55])

In [36]:
a[:, 1:6:2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25],
       [31, 33, 35],
       [41, 43, 45],
       [51, 53, 55]])

## 3. 데이터프레임 만들기

In [37]:
import pandas as pd

In [38]:
pd.DataFrame([['cat','mango'],['dog','orange'],['lion','melon']],index=[0,1,2],columns=['animal','fruit'])

animal   fruit
0    cat   mango
1    dog  orange
2   lion   melon

In [39]:
pd.DataFrame([['cat','mango'],['dog','orange'],['lion','melon']],columns=['animal','fruit'])

animal   fruit
0    cat   mango
1    dog  orange
2   lion   melon

In [42]:
a = pd.DataFrame({'animal':['cat','dog','lion'],'fruit':['mango','orange','melon']}) 
a

animal   fruit
0    cat   mango
1    dog  orange
2   lion   melon

### 3-1. 망고와 멜론만 뽑으세요

In [52]:
a['fruit'][::2]

a.iloc[[0,2],[1]]

a.iloc[[0,2]][['fruit']] 

a.loc[:,'fruit'][[0,2]]

a.loc[:,'fruit'][::2] # a.loc[:,1][::2]

a.iloc[:,1][[0,2]]

a['fruit'][[0,2]]

a.fruit[[0,2]]

0    mango
2    melon
Name: fruit, dtype: object

## 4. name과 job 열 뽑기

In [55]:
df = pd.DataFrame([['John',25,'student'],['Cho',30,'teacher']],
                           columns= ['Name','Age','Job']) 
df

Name  Age      Job
0  John   25  student
1   Cho   30  teacher

In [57]:
df[['Name',"Job"]]

Name      Job
0  John  student
1   Cho  teacher

In [62]:
df.iloc[:,::2]

Name      Job
0  John  student
1   Cho  teacher

## 5. np.min 과 np.argmin의 차이점은?

In [65]:
a = np.array([[3,5,1],[2,4,6]])
a 

array([[3, 5, 1],
       [2, 4, 6]])

In [66]:
np.min(a)

1

In [67]:
np.argmin(a)

2

## 6. 랜덤으로  5x5 행렬 만들기 

In [68]:
import random

In [75]:
np.array(random.sample(range(25),k=25)).reshape(5,5)

array([[24, 14, 20,  5,  2],
       [23,  0,  7,  6, 21],
       [ 4,  3, 16,  9, 18],
       [15, 13, 17, 22, 19],
       [ 1,  8, 11, 10, 12]])

In [86]:
np.random.randint(0,25,size=(5,5))

array([[14,  7, 12,  7, 15],
       [22,  2,  5, 24,  1],
       [16, 10, 14,  7, 16],
       [ 7,  5, 16, 12,  9],
       [16,  8, 19, 15, 10]])

In [82]:
li = list(range(25))
random.shuffle(li)
np.array(li).reshape(5,5)

array([[15, 24, 10,  0, 23],
       [22,  2, 13,  3,  5],
       [18,  8, 14,  1,  6],
       [20,  4, 17, 11, 19],
       [ 7, 16,  9, 21, 12]])

In [84]:

np.array(random.shuffle(list(range(25)))).reshape(5,5)

ValueError: cannot reshape array of size 1 into shape (5,5)

### 6-1. 최댓값을 구하세요

In [87]:
random.seed(1234)
a = np.array(random.sample(li,k=25)).reshape(5,5)
a 

array([[12,  6,  0, 15, 10],
       [11, 24,  7,  9,  8],
       [ 4, 16,  1, 14, 22],
       [ 5, 13,  3, 19, 20],
       [ 2, 18, 21, 23, 17]])

In [88]:
a.max()

24

### 6-2. 행별 최댓값.

In [91]:
np.max(a,axis=1)

array([15, 24, 22, 20, 23])

# 2교시 

## 7. 서준이 점수를 0점으로 

In [106]:
df = pd.DataFrame([[90,98,95,100],[80,89,95,90],[60,65,80,90]],
                 index=['서준','우현','인아'],
                 columns=['수학','영어','음악','체육'])
df 

수학  영어  음악   체육
서준  90  98  95  100
우현  80  89  95   90
인아  60  65  80   90

In [96]:
df.loc[["서준"]]=0
df

수학  영어  음악  체육
서준   0   0   0   0
우현  80  89  95  90
인아  60  65  80  90

In [104]:
df.iloc[[0],:]=0
df

수학  영어  음악  체육
서준   0   0   0   0
우현  80  89  95  90
인아  60  65  80  90

In [109]:
df[:1]=0
df

수학  영어  음악  체육
서준   0   0   0   0
우현  80  89  95  90
인아  60  65  80  90

In [134]:
import plotly.express as px
df = px.data.gapminder() 
df 

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0     Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1     Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2     Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3     Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4     Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   
...           ...       ...   ...      ...       ...         ...       ...   
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306       ZWE   
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786       ZWE   
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960       ZWE   
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623       ZWE   
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
0           4  
1           4  
2           4  
3           4  
4           4  
...       ...  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716  

[1704 rows x 8 columns]

## 8. country와 continent 정보만 뽑아주세요

In [133]:
df.iloc[:,:2]

df[['country','continent']]

df.loc[:,['country','continent']]

country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
1699     Zimbabwe    Africa
1700     Zimbabwe    Africa
1701     Zimbabwe    Africa
1702     Zimbabwe    Africa
1703     Zimbabwe    Africa

[1704 rows x 2 columns]

### 8-1. 이름을 '나라' , '대륙' 으로 수정하세요

In [128]:
df.rename(columns={"country":"나라",'continent':"대륙"})
# 저장은 안되어있음

나라      대륙  year  lifeExp       pop   gdpPercap iso_alpha  \
0     Afghanistan    Asia  1952   28.801   8425333  779.445314       AFG   
1     Afghanistan    Asia  1957   30.332   9240934  820.853030       AFG   
2     Afghanistan    Asia  1962   31.997  10267083  853.100710       AFG   
3     Afghanistan    Asia  1967   34.020  11537966  836.197138       AFG   
4     Afghanistan    Asia  1972   36.088  13079460  739.981106       AFG   
...           ...     ...   ...      ...       ...         ...       ...   
1699     Zimbabwe  Africa  1987   62.351   9216418  706.157306       ZWE   
1700     Zimbabwe  Africa  1992   60.377  10704340  693.420786       ZWE   
1701     Zimbabwe  Africa  1997   46.809  11404948  792.449960       ZWE   
1702     Zimbabwe  Africa  2002   39.989  11926563  672.038623       ZWE   
1703     Zimbabwe  Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
0           4  
1           4  
2           4  
3           4  
4           4  
...       ...  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716  

[1704 rows x 8 columns]

### 8-2. 맨 마지막부터 3열을 삭제하고 저장하세요

In [135]:
z = df.iloc[:,:-3]

In [136]:
z

country continent  year  lifeExp       pop
0     Afghanistan      Asia  1952   28.801   8425333
1     Afghanistan      Asia  1957   30.332   9240934
2     Afghanistan      Asia  1962   31.997  10267083
3     Afghanistan      Asia  1967   34.020  11537966
4     Afghanistan      Asia  1972   36.088  13079460
...           ...       ...   ...      ...       ...
1699     Zimbabwe    Africa  1987   62.351   9216418
1700     Zimbabwe    Africa  1992   60.377  10704340
1701     Zimbabwe    Africa  1997   46.809  11404948
1702     Zimbabwe    Africa  2002   39.989  11926563
1703     Zimbabwe    Africa  2007   43.487  12311143

[1704 rows x 5 columns]

In [137]:
df.drop(['gdpPercap','iso_alpha','iso_num'],axis=1)

country continent  year  lifeExp       pop
0     Afghanistan      Asia  1952   28.801   8425333
1     Afghanistan      Asia  1957   30.332   9240934
2     Afghanistan      Asia  1962   31.997  10267083
3     Afghanistan      Asia  1967   34.020  11537966
4     Afghanistan      Asia  1972   36.088  13079460
...           ...       ...   ...      ...       ...
1699     Zimbabwe    Africa  1987   62.351   9216418
1700     Zimbabwe    Africa  1992   60.377  10704340
1701     Zimbabwe    Africa  1997   46.809  11404948
1702     Zimbabwe    Africa  2002   39.989  11926563
1703     Zimbabwe    Africa  2007   43.487  12311143

[1704 rows x 5 columns]

In [139]:
df.drop(['gdpPercap','iso_alpha','iso_num'],axis=1,inplace=True)

In [140]:
df

country continent  year  lifeExp       pop
0     Afghanistan      Asia  1952   28.801   8425333
1     Afghanistan      Asia  1957   30.332   9240934
2     Afghanistan      Asia  1962   31.997  10267083
3     Afghanistan      Asia  1967   34.020  11537966
4     Afghanistan      Asia  1972   36.088  13079460
...           ...       ...   ...      ...       ...
1699     Zimbabwe    Africa  1987   62.351   9216418
1700     Zimbabwe    Africa  1992   60.377  10704340
1701     Zimbabwe    Africa  1997   46.809  11404948
1702     Zimbabwe    Africa  2002   39.989  11926563
1703     Zimbabwe    Africa  2007   43.487  12311143

[1704 rows x 5 columns]

### 8-3. 2002년부터 이후의 데이터만 출력하세요

In [141]:
df[df.year>=2002]

country continent  year  lifeExp       pop
10    Afghanistan      Asia  2002   42.129  25268405
11    Afghanistan      Asia  2007   43.828  31889923
22        Albania    Europe  2002   75.651   3508512
23        Albania    Europe  2007   76.423   3600523
34        Algeria    Africa  2002   70.994  31287142
...           ...       ...   ...      ...       ...
1679  Yemen, Rep.      Asia  2007   62.698  22211743
1690       Zambia    Africa  2002   39.193  10595811
1691       Zambia    Africa  2007   42.384  11746035
1702     Zimbabwe    Africa  2002   39.989  11926563
1703     Zimbabwe    Africa  2007   43.487  12311143

[284 rows x 5 columns]

## 9. 행렬을 만들어보세요

In [160]:
a = pd.DataFrame([[20,'AB',"서울"],[25,'B',"강원"],[27,'A',"경기"]],index=["길동","춘향","몽룡"],columns=["이름","혈액형","거주지"])
a

이름 혈액형 거주지
길동  20  AB  서울
춘향  25   B  강원
몽룡  27   A  경기

### 9-1. 길동이를 빼주세요

In [149]:
a[1:]

이름 혈액형 거주지
춘향  25   B  강원
몽룡  27   A  경기

In [171]:
a.loc["춘향":]

이름 혈액형 거주지
춘향  25   B  강원
몽룡  27   A  경기

### 9-2. 거주지 열 이름을 '출생지' 로 바꾸고 저장하세요

In [165]:
a.rename(columns={"거주지":"출생지"})

이름 혈액형 출생지
길동  20  AB  서울
춘향  25   B  강원
몽룡  27   A  경기

## PPT : 행 추가, 열 추가

In [173]:
df = pd.DataFrame([[90,98,95,100],[80,89,95,90],[60,65,80,90]],
                 index=['서준','우현','인아'],
                 columns=['수학','영어','음악','체육'])
df 

수학  영어  음악   체육
서준  90  98  95  100
우현  80  89  95   90
인아  60  65  80   90

In [174]:
df.loc["인아"] = [0,0,0,0]

### 행 추가

In [179]:
# 있으면 덮어쓰고 없으면 새롭게 만들어서 추가해라
df.loc["상기"] = [95,100,80,95] 

In [178]:
df

수학   영어  음악   체육
서준  90   98  95  100
우현  80   89  95   90
인아   0    0   0    0
상기  95  100  80   95

### 열 추가

In [182]:
df['미술'] = [80,90,95,100]

In [181]:
df

수학   영어  음악   체육   미술
서준  90   98  95  100   80
우현  80   89  95   90   90
인아   0    0   0    0   95
상기  95  100  80   95  100

### 원소 선택(조회)

### 원소 값 바꾸기

In [195]:
df.loc["인아",["체육","영어"]] = 80,90

In [196]:
df

수학   영어  음악   체육   미술
서준  90   98  95  100   80
우현  80   89  95   90   90
인아   0   90   0   80   95
상기  95  100  80   95  100

# 3교시 : 파일 읽기

In [239]:
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/auto-mpg.csv')
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

## 파일 저장하기

In [ ]:
df.to_csv()

### quiz

In [210]:
df.rename(columns={"displacement":"displ","model-year":"year"},inplace=True)

In [212]:
df[df.year>=75]

mpg  cylinders  displ  horsepower  weight  acceleration  year
152  19.0          6  225.0        95.0    3264          16.0    75
153  18.0          6  250.0       105.0    3459          16.0    75
154  15.0          6  250.0        72.0    3432          21.0    75
155  15.0          6  250.0        72.0    3158          19.5    75
156  16.0          8  400.0       170.0    4668          11.5    75
..    ...        ...    ...         ...     ...           ...   ...
393  27.0          4  140.0        86.0    2790          15.6    82
394  44.0          4   97.0        52.0    2130          24.6    82
395  32.0          4  135.0        84.0    2295          11.6    82
396  28.0          4  120.0        79.0    2625          18.6    82
397  31.0          4  119.0        82.0    2720          19.4    82

[246 rows x 7 columns]

In [213]:
df['year'] = df['year'] + 1900

In [214]:
df

mpg  cylinders  displ  horsepower  weight  acceleration  year
0    18.0          8  307.0       130.0    3504          12.0  1970
1    15.0          8  350.0       165.0    3693          11.5  1970
2    18.0          8  318.0       150.0    3436          11.0  1970
3    16.0          8  304.0       150.0    3433          12.0  1970
4    17.0          8  302.0       140.0    3449          10.5  1970
..    ...        ...    ...         ...     ...           ...   ...
393  27.0          4  140.0        86.0    2790          15.6  1982
394  44.0          4   97.0        52.0    2130          24.6  1982
395  32.0          4  135.0        84.0    2295          11.6  1982
396  28.0          4  120.0        79.0    2625          18.6  1982
397  31.0          4  119.0        82.0    2720          19.4  1982

[398 rows x 7 columns]

### quiz) df를 mpg.csv로 저장해주세요

In [236]:
df.to_csv("mpg.csv")

### 엑셀파일 불러오기

In [232]:
import os
os.getcwd()

'C:\\Users\\user\\anacon'

In [235]:
df = pd.read_excel("./Presidents.xlsx")
df

President  Years in office  Year first inaugurated  \
0        George Washington              8.0                    1789   
1               John Adams              4.0                    1797   
2         Thomas Jefferson              8.0                    1801   
3            James Madison              8.0                    1809   
4             James Monroe              8.0                    1817   
5        John Quincy Adams              4.0                    1825   
6           Andrew Jackson              8.0                    1829   
7        Martin Van Buren               4.0                    1837   
8   William Henry Harrison              0.8                    1841   
9            James K. Polk              4.0                    1845   
10          Zachary Taylor              1.0                    1849   
11         Franklin Pierce              4.0                    1853   
12          James Buchanan              4.0                    1857   
13         Abraham Lincoln              4.0                    1861   
14        Ulysses S. Grant              8.0                    1869   
15     Rutherford B. Hayes              4.0                    1877   
16       James A. Garfield              0.5                    1881   
17        Grover Cleveland              4.0                    1885   
18       Benjamin Harrison              4.0                    1889   
19        Grover Cleveland              4.0                    1893   
20        William McKinley              4.0                    1897   
21     William Howard Taft              4.0                    1909   
22          Woodrow Wilson              8.0                    1913   
23       Warren G. Harding              2.0                    1921   
24          Herbert Hoover              4.0                    1929   
25      Franklin Roosevelt             12.0                    1933   
26    Dwight D. Eisenhower              8.0                    1953   
27         John F. Kennedy              3.0                    1961   
28        Richard M. Nixon              5.0                    1969   
29            Jimmy Carter              4.0                    1977   
30           Ronald Reagan              8.0                    1981   
31             George Bush              4.0                    1989   
32            Bill Clinton              8.0                    1993   
33          George W. Bush              8.0                    2001   
34            Barack Obama              NaN                    2009   

    Age at inauguration State elected from  # of electoral votes  \
0                    57           Virginia                    69   
1                    61      Massachusetts                   132   
2                    57           Virginia                    73   
3                    57           Virginia                   122   
4                    58           Virginia                   183   
5                    57      Massachusetts                    84   
6                    61          Tennessee                   178   
7                    54           New York                   170   
8                    68               Ohio                   234   
9                    49          Tennessee                   170   
10                   64          Louisiana                   163   
11                   48      New Hampshire                   254   
12                   65       Pennsylvania                   174   
13                   52           Illinois                   180   
14                   46           Illinois                   214   
15                   54               Ohio                   185   
16                   49               Ohio                   214   
17                   47           New York                   219   
18                   55            Indiana                   233   
19                   55           New York                   277   
20                   54         

In [240]:
df.head(2)

mpg  cylinders  displacement  horsepower  weight  acceleration  model-year
0  18.0          8         307.0       130.0    3504          12.0          70
1  15.0          8         350.0       165.0    3693          11.5          70

In [241]:
df.describe() # summary

mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  396.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.189394  2970.424623   
std      7.815984    1.701004    104.269838   38.402030   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   92.000000  2803.500000   
75%     29.000000    8.000000    262.000000  125.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model-year  
count    398.000000  398.000000  
mean      15.568090   76.010050  
std        2.757689    3.697627  
min        8.000000   70.000000  
25%       13.825000   73.000000  
50%       15.500000   76.000000  
75%       17.175000   79.000000  
max       24.800000   82.000000

In [242]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    396 non-null    float64
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model-year    398 non-null    int64  
dtypes: float64(4), int64(3)
memory usage: 21.9 KB


In [243]:
df.shape

(398, 7)

In [244]:
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight            int64
acceleration    float64
model-year        int64
dtype: object

In [245]:
df.size

2786

In [246]:
df.count

<bound method DataFrame.count of       mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4           

In [247]:
df['cylinders']

0      8
1      8
2      8
3      8
4      8
      ..
393    4
394    4
395    4
396    4
397    4
Name: cylinders, Length: 398, dtype: int64

In [248]:
df['cylinders'].count()

398

In [250]:
# 중요한 메소드
df['cylinders'].value_counts() 
# 입력값 : 시리즈 
# 아웃풋 : 시리즈

4    204
8    103
6     84
3      4
5      3
Name: cylinders, dtype: int64

In [251]:
df.value_counts

<bound method DataFrame.value_counts of       mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4    

In [252]:
df['cylinders'].unique()

array([8, 4, 6, 3, 5], dtype=int64)

In [254]:
df.mean()

mpg               23.514573
cylinders          5.454774
displacement     193.425879
horsepower       104.189394
weight          2970.424623
acceleration      15.568090
model-year        76.010050
dtype: float64

In [255]:
np.mean(df)

C:\Users\user\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:3430: FutureWarning: In a future version, DataFrame.mean(axis=None) will return a scalar mean over the entire DataFrame. To retain the old behavior, use 'frame.mean(axis=0)' or just 'frame.mean()'
  return mean(axis=axis, dtype=dtype, out=out, **kwargs)


mpg               23.514573
cylinders          5.454774
displacement     193.425879
horsepower       104.189394
weight          2970.424623
acceleration      15.568090
model-year        76.010050
dtype: float64

In [256]:
np.mean(df, axis=1)

0      578.428571
1      616.071429
2      573.000000
3      570.428571
4      570.928571
          ...    
393    449.228571
394    347.657143
395    377.657143
396    422.371429
397    436.771429
Length: 398, dtype: float64

In [257]:
df.values

array([[  18. ,    8. ,  307. , ..., 3504. ,   12. ,   70. ],
       [  15. ,    8. ,  350. , ..., 3693. ,   11.5,   70. ],
       [  18. ,    8. ,  318. , ..., 3436. ,   11. ,   70. ],
       ...,
       [  32. ,    4. ,  135. , ..., 2295. ,   11.6,   82. ],
       [  28. ,    4. ,  120. , ..., 2625. ,   18.6,   82. ],
       [  31. ,    4. ,  119. , ..., 2720. ,   19.4,   82. ]])

# 5교시

## 상관계수 구하기 



In [261]:
df.corr()

mpg  cylinders  displacement  horsepower    weight  \
mpg           1.000000  -0.775396     -0.804203   -0.777575 -0.831741   
cylinders    -0.775396   1.000000      0.950721    0.843751  0.896017   
displacement -0.804203   0.950721      1.000000    0.897787  0.932824   
horsepower   -0.777575   0.843751      0.897787    1.000000  0.864350   
weight       -0.831741   0.896017      0.932824    0.864350  1.000000   
acceleration  0.420289  -0.505419     -0.543684   -0.687241 -0.417457   
model-year    0.579267  -0.348746     -0.370164   -0.420697 -0.306564   

              acceleration  model-year  
mpg               0.420289    0.579267  
cylinders        -0.505419   -0.348746  
displacement     -0.543684   -0.370164  
horsepower       -0.687241   -0.420697  
weight           -0.417457   -0.306564  
acceleration      1.000000    0.288137  
model-year        0.288137    1.000000

## 결측치

In [ ]:
import seaborn as sns

In [265]:
titanic= pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [266]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [269]:
titanic[:2]

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   

   Parch     Ticket     Fare Cabin Embarked  
0      0  A/5 21171   7.2500   NaN        S  
1      0   PC 17599  71.2833   C85        C

In [271]:
titanic.isnull()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 12 columns]

In [274]:
titanic.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [275]:
titanic.dropna().info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  183 non-null    int64  
 1   Survived     183 non-null    int64  
 2   Pclass       183 non-null    int64  
 3   Name         183 non-null    object 
 4   Sex          183 non-null    object 
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64  
 7   Parch        183 non-null    int64  
 8   Ticket       183 non-null    object 
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object 
 11  Embarked     183 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB


In [276]:
titanic.dropna(axis =1).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   SibSp        891 non-null    int64  
 6   Parch        891 non-null    int64  
 7   Ticket       891 non-null    object 
 8   Fare         891 non-null    float64
dtypes: float64(1), int64(5), object(3)
memory usage: 62.8+ KB


## 결측치 대체하기

In [278]:
# 평균값으로 대체하기
mean_age = titanic['Age'].mean()
titanic['Age'].fillna(mean_age,inplace=True)


In [279]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [280]:
titanic["Age"].isnull()

0      False
1      False
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

## 중복데이터

### 중복된 행의 개수 : df.duplicated()

### 중복행 제거 : df.drop_duplicated()

## 데이터프레임 합치기 : concat

In [292]:
# 시리즈 + 시리즈

In [283]:
E = pd.Series(['e0','e1','e2','e3'],name='e')
F = pd.Series(['f0','f1','f2'],name='f',index=[3,4,5])
G = pd.Series(['g0','g1','g2','g3'],name='g')

In [284]:
E

0    e0
1    e1
2    e2
3    e3
Name: e, dtype: object

In [285]:
F

3    f0
4    f1
5    f2
Name: f, dtype: object

In [286]:
G

0    g0
1    g1
2    g2
3    g3
Name: g, dtype: object

In [288]:
pd.concat([E,F])

0    e0
1    e1
2    e2
3    e3
3    f0
4    f1
5    f2
dtype: object

In [289]:
pd.concat([E,F],axis=1)

e    f
0   e0  NaN
1   e1  NaN
2   e2  NaN
3   e3   f0
4  NaN   f1
5  NaN   f2

In [290]:
pd.concat([E,G])

0    e0
1    e1
2    e2
3    e3
0    g0
1    g1
2    g2
3    g3
dtype: object

In [291]:
pd.concat([E,G],axis=1)

e   g
0  e0  g0
1  e1  g1
2  e2  g2
3  e3  g3

In [293]:
# 데이터프레임 + 데이터프레임

In [294]:
df1 = pd.DataFrame({'a':['a0','a1','a2'],'b':['b0','b1','b2'],'c':['c0','c1','c2']},index=[0,1,2])

In [304]:
df2 = pd.DataFrame({'b':['b2','b3','b4'],'c':['c2','c3','c4'],'d':['d2','d3','d4']},index=[1,2,3])

In [305]:
df1

a   b   c
0  a0  b0  c0
1  a1  b1  c1
2  a2  b2  c2

In [306]:
df2

b   c   d
1  b2  c2  d2
2  b3  c3  d3
3  b4  c4  d4

In [307]:
pd.concat([df1,df2])

a   b   c    d
0   a0  b0  c0  NaN
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
1  NaN  b2  c2   d2
2  NaN  b3  c3   d3
3  NaN  b4  c4   d4

In [308]:
pd.concat([df1,df2],axis=1)

a    b    c    b    c    d
0   a0   b0   c0  NaN  NaN  NaN
1   a1   b1   c1   b2   c2   d2
2   a2   b2   c2   b3   c3   d3
3  NaN  NaN  NaN   b4   c4   d4

In [309]:
pd.concat([df1,df2],axis=1,join='inner')

a   b   c   b   c   d
1  a1  b1  c1  b2  c2  d2
2  a2  b2  c2  b3  c3  d3

# 6교시

## 칼럼 이름 모두 소문자로 바꾸기

In [312]:
new_columns = []
for column in titanic.columns:
    new_columns.append(column.lower())
titanic.columns = new_columns 

In [487]:
titanic

passengerid  survived  pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  name     sex        age  \
0                              Braund, Mr. Owen Harris    male  22.000000   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000   
2                               Heikkinen, Miss. Laina  female  26.000000   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000   
4                             Allen, Mr. William Henry    male  35.000000   
..                                                 ...     ...        ...   
886                              Montvila, Rev. Juozas    male  27.000000   
887                       Graham, Miss. Margaret Edith  female  19.000000   
888           Johnston, Miss. Catherine Helen "Carrie"  female  29.699118   
889                              Behr, Mr. Karl Howell    male  26.000000   
890                                Dooley, Mr. Patrick    male  32.000000   

     sibsp  parch            ticket     fare cabin embarked  
0        1      0         A/5 21171   7.2500   NaN        S  
1        1      0          PC 17599  71.2833   C85        C  
2        0      0  STON/O2. 3101282   7.9250   NaN        S  
3        1      0            113803  53.1000  C123        S  
4        0      0            373450   8.0500   NaN        S  
..     ...    ...               ...      ...   ...      ...  
886      0      0            211536  13.0000   NaN        S  
887      0      0            112053  30.0000   B42        S  
888      1      2        W./C. 6607  23.4500   NaN        S  
889      0      0            111369  30.0000  C148        C  
890      0      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [314]:
new_columns = [column.lower() for column in titanic.columns]
titanic.columns = new_columns

In [316]:
new_columns

['passengerid',
 'survived',
 'pclass',
 'name',
 'sex',
 'age',
 'sibsp',
 'parch',
 'ticket',
 'fare',
 'cabin',
 'embarked']

In [318]:
titanic.columns = map(lambda x: x.lower(), list(titanic.columns))

In [488]:
titanic.columns

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='object')

In [441]:
list[titanic.columns]

list[Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp',
       'parch', 'ticket', 'fare', 'cabin', 'embarked'],
      dtype='object')]

In [489]:
titanic.columns.str.capitalize()

Index(['Passengerid', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Sibsp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [324]:
titanic['name'].str.upper()

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...                        
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: name, Length: 891, dtype: object

In [325]:
all_data = [['John', 'Emily', 'Michael', 'Mary', 'Steven'],
              ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]
all_data 

[['John', 'Emily', 'Michael', 'Mary', 'Steven'],
 ['Maria', 'Juan', 'Javier', 'Natalia', 'Pilar']]

## 하나의 리스트에 담기 : names = []

In [326]:
names = [j for i in all_data for j in i]

In [327]:
names

['John',
 'Emily',
 'Michael',
 'Mary',
 'Steven',
 'Maria',
 'Juan',
 'Javier',
 'Natalia',
 'Pilar']

### e가 2번 이상 들어간 사람 고르기

In [330]:
for name in names:
      if name.count("e") >= 2:
            print(name)

Steven


In [332]:
[name for name in names if name.count("e")>=2]

['Steven']

# 7교시

In [335]:
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [348]:
labels = pd.Index(['mandoo','po','dump','pling'])
labels

Index(['mandoo', 'po', 'dump', 'pling'], dtype='object')

In [349]:
dup_labels.append(labels)

Index(['foo', 'foo', 'bar', 'bar', 'mandoo', 'po', 'dump', 'pling'], dtype='object')

In [350]:
dup_labels.is_unique # 중복되는 색인이 있으면 False

False

In [352]:
labels.is_unique

True

In [356]:
dup_labels.unique

<bound method Index.unique of Index(['foo', 'foo', 'bar', 'bar'], dtype='object')>

In [357]:
df = pd.DataFrame()
df['A'] = [1, 2, 3, np.nan, 7, 7]
df['B'] = ['b', 'b', 'b', 'c', np.nan, 'd']


In [358]:
df

A    B
0  1.0    b
1  2.0    b
2  3.0    b
3  NaN    c
4  7.0  NaN
5  7.0    d

In [363]:
z = df['A'].unique()

In [364]:
x = df['B'].unique()

In [361]:
df['A']

0    1.0
1    2.0
2    3.0
3    NaN
4    7.0
5    7.0
Name: A, dtype: float64

In [362]:
df

A    B
0  1.0    b
1  2.0    b
2  3.0    b
3  NaN    c
4  7.0  NaN
5  7.0    d

In [365]:
z

array([ 1.,  2.,  3., nan,  7.])

In [366]:
x

array(['b', 'c', nan, 'd'], dtype=object)

In [370]:
z.

IndexError: index 5 is out of bounds for axis 0 with size 5

In [371]:
df.drop_duplicates

A    B
0  1.0    b
1  2.0    b
2  3.0    b
3  NaN    c
4  7.0  NaN
5  7.0    d

# 8교시 - 숙제 출제

In [491]:
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/auto-mpg.csv')
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

In [377]:
df.sort_index(ascending = False)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
397  31.0          4         119.0        82.0    2720          19.4   
396  28.0          4         120.0        79.0    2625          18.6   
395  32.0          4         135.0        84.0    2295          11.6   
394  44.0          4          97.0        52.0    2130          24.6   
393  27.0          4         140.0        86.0    2790          15.6   
..    ...        ...           ...         ...     ...           ...   
4    17.0          8         302.0       140.0    3449          10.5   
3    16.0          8         304.0       150.0    3433          12.0   
2    18.0          8         318.0       150.0    3436          11.0   
1    15.0          8         350.0       165.0    3693          11.5   
0    18.0          8         307.0       130.0    3504          12.0   

     model-year  
397          82  
396          82  
395          82  
394          82  
393          82  
..          ...  
4            70  
3            70  
2            70  
1            70  
0            70  

[398 rows x 7 columns]

In [427]:
df

acceleration cylinders displacement horsepower model-year   mpg weight
0           18.0         8        307.0      130.0       3504  12.0     70
1           15.0         8        350.0      165.0       3693  11.5     70
2           18.0         8        318.0      150.0       3436  11.0     70
3           16.0         8        304.0      150.0       3433  12.0     70
4           17.0         8        302.0      140.0       3449  10.5     70
..           ...       ...          ...        ...        ...   ...    ...
393         27.0         4        140.0       86.0       2790  15.6     82
394         44.0         4         97.0       52.0       2130  24.6     82
395         32.0         4        135.0       84.0       2295  11.6     82
396         28.0         4        120.0       79.0       2625  18.6     82
397         31.0         4        119.0       82.0       2720  19.4     82

[398 rows x 7 columns]

In [420]:
list(df)

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model-year']

In [422]:
w = list(df)
w

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model-year']

In [423]:
w.sort()

In [424]:
w

['acceleration',
 'cylinders',
 'displacement',
 'horsepower',
 'model-year',
 'mpg',
 'weight']

In [425]:
df.columns = [w]

In [426]:
df

acceleration cylinders displacement horsepower model-year   mpg weight
0           18.0         8        307.0      130.0       3504  12.0     70
1           15.0         8        350.0      165.0       3693  11.5     70
2           18.0         8        318.0      150.0       3436  11.0     70
3           16.0         8        304.0      150.0       3433  12.0     70
4           17.0         8        302.0      140.0       3449  10.5     70
..           ...       ...          ...        ...        ...   ...    ...
393         27.0         4        140.0       86.0       2790  15.6     82
394         44.0         4         97.0       52.0       2130  24.6     82
395         32.0         4        135.0       84.0       2295  11.6     82
396         28.0         4        120.0       79.0       2625  18.6     82
397         31.0         4        119.0       82.0       2720  19.4     82

[398 rows x 7 columns]

In [389]:
q = df.columns.values.tolist()
q

['mpg',
 'cylinders',
 'displacement',
 'horsepower',
 'weight',
 'acceleration',
 'model-year']

In [390]:
q.sort()

In [391]:
q

['acceleration',
 'cylinders',
 'displacement',
 'horsepower',
 'model-year',
 'mpg',
 'weight']

In [392]:
np.sort(q)

array(['acceleration', 'cylinders', 'displacement', 'horsepower',
       'model-year', 'mpg', 'weight'], dtype='<U12')

In [394]:
df.columns = [q]

In [396]:
df.columns

MultiIndex([('acceleration',),
            (   'cylinders',),
            ('displacement',),
            (  'horsepower',),
            (  'model-year',),
            (         'mpg',),
            (      'weight',)],
           )

In [397]:
df

acceleration cylinders displacement horsepower model-year   mpg weight
0           18.0         8        307.0      130.0       3504  12.0     70
1           15.0         8        350.0      165.0       3693  11.5     70
2           18.0         8        318.0      150.0       3436  11.0     70
3           16.0         8        304.0      150.0       3433  12.0     70
4           17.0         8        302.0      140.0       3449  10.5     70
..           ...       ...          ...        ...        ...   ...    ...
393         27.0         4        140.0       86.0       2790  15.6     82
394         44.0         4         97.0       52.0       2130  24.6     82
395         32.0         4        135.0       84.0       2295  11.6     82
396         28.0         4        120.0       79.0       2625  18.6     82
397         31.0         4        119.0       82.0       2720  19.4     82

[398 rows x 7 columns]

# Q1
```
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/auto-mpg.csv')
w = list(df)
w.sort()
df.columns = [w]
df
```

In [429]:
list(df).sort

<function list.sort(*, key=None, reverse=False)>

In [434]:
np.sort(list(df))

array([['mpg'],
       ['cylinders'],
       ['displacement'],
       ['horsepower'],
       ['weight'],
       ['acceleration'],
       ['model-year']], dtype='<U12')

In [432]:
df.columns = [list(df).sort()]

ValueError: Length mismatch: Expected axis has 7 elements, new values have 1 elements

In [444]:
df

acceleration cylinders displacement horsepower model-year   mpg weight
0           18.0         8        307.0      130.0       3504  12.0     70
1           15.0         8        350.0      165.0       3693  11.5     70
2           18.0         8        318.0      150.0       3436  11.0     70
3           16.0         8        304.0      150.0       3433  12.0     70
4           17.0         8        302.0      140.0       3449  10.5     70
..           ...       ...          ...        ...        ...   ...    ...
393         27.0         4        140.0       86.0       2790  15.6     82
394         44.0         4         97.0       52.0       2130  24.6     82
395         32.0         4        135.0       84.0       2295  11.6     82
396         28.0         4        120.0       79.0       2625  18.6     82
397         31.0         4        119.0       82.0       2720  19.4     82

[398 rows x 7 columns]

In [456]:
df.columns.sort

<bound method Index.sort of Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model-year'],
      dtype='object')>

In [457]:
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

In [ ]:
titanic.columns.str.lower()

In [458]:
new_columns = [column.capitalize() for column in df.columns]
df.columns = new_columns

In [485]:
df.columns

MultiIndex([('Acceleration',),
            (   'Cylinders',),
            ('Displacement',),
            (  'Horsepower',),
            (  'Model-year',),
            (         'Mpg',),
            (      'Weight',)],
           )

In [484]:
df

Acceleration Cylinders Displacement Horsepower Model-year   Mpg Weight
0           18.0         8        307.0      130.0       3504  12.0     70
1           15.0         8        350.0      165.0       3693  11.5     70
2           18.0         8        318.0      150.0       3436  11.0     70
3           16.0         8        304.0      150.0       3433  12.0     70
4           17.0         8        302.0      140.0       3449  10.5     70
..           ...       ...          ...        ...        ...   ...    ...
393         27.0         4        140.0       86.0       2790  15.6     82
394         44.0         4         97.0       52.0       2130  24.6     82
395         32.0         4        135.0       84.0       2295  11.6     82
396         28.0         4        120.0       79.0       2625  18.6     82
397         31.0         4        119.0       82.0       2720  19.4     82

[398 rows x 7 columns]

In [474]:
a = list(df)

In [475]:
a

['Mpg',
 'Cylinders',
 'Displacement',
 'Horsepower',
 'Weight',
 'Acceleration',
 'Model-year']

In [478]:
a.sort()

In [479]:
a

['Acceleration',
 'Cylinders',
 'Displacement',
 'Horsepower',
 'Model-year',
 'Mpg',
 'Weight']

In [480]:
df.columns = [a]

In [481]:
df.columns

MultiIndex([('Acceleration',),
            (   'Cylinders',),
            ('Displacement',),
            (  'Horsepower',),
            (  'Model-year',),
            (         'Mpg',),
            (      'Weight',)],
           )

In [482]:
df.columns

Acceleration Cylinders Displacement Horsepower Model-year   Mpg Weight
0           18.0         8        307.0      130.0       3504  12.0     70
1           15.0         8        350.0      165.0       3693  11.5     70
2           18.0         8        318.0      150.0       3436  11.0     70
3           16.0         8        304.0      150.0       3433  12.0     70
4           17.0         8        302.0      140.0       3449  10.5     70
..           ...       ...          ...        ...        ...   ...    ...
393         27.0         4        140.0       86.0       2790  15.6     82
394         44.0         4         97.0       52.0       2130  24.6     82
395         32.0         4        135.0       84.0       2295  11.6     82
396         28.0         4        120.0       79.0       2625  18.6     82
397         31.0         4        119.0       82.0       2720  19.4     82

[398 rows x 7 columns]

In [ ]:

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/auto-mpg.csv')
w = list(df)
w.sort()
df.columns = [w]
df


# Q2

In [ ]:
a = df.columns.str.capitalize()

In [499]:
a

Index(['Mpg', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
       'Acceleration', 'Model-year'],
      dtype='object')

In [505]:
df.columns = a

In [510]:
b = df.columns

In [516]:
c = list(b)

In [517]:
c

['Mpg',
 'Cylinders',
 'Displacement',
 'Horsepower',
 'Weight',
 'Acceleration',
 'Model-year']

In [518]:
c.sort()

In [519]:
c

['Acceleration',
 'Cylinders',
 'Displacement',
 'Horsepower',
 'Model-year',
 'Mpg',
 'Weight']

In [520]:
df.columns = c

In [521]:
df

Acceleration  Cylinders  Displacement  Horsepower  Model-year   Mpg  \
0            18.0          8         307.0       130.0        3504  12.0   
1            15.0          8         350.0       165.0        3693  11.5   
2            18.0          8         318.0       150.0        3436  11.0   
3            16.0          8         304.0       150.0        3433  12.0   
4            17.0          8         302.0       140.0        3449  10.5   
..            ...        ...           ...         ...         ...   ...   
393          27.0          4         140.0        86.0        2790  15.6   
394          44.0          4          97.0        52.0        2130  24.6   
395          32.0          4         135.0        84.0        2295  11.6   
396          28.0          4         120.0        79.0        2625  18.6   
397          31.0          4         119.0        82.0        2720  19.4   

     Weight  
0        70  
1        70  
2        70  
3        70  
4        70  
..      ...  
393      82  
394      82  
395      82  
396      82  
397      82  

[398 rows x 7 columns]