# 1교시

In [4]:
import numpy as np
import pandas as pd

## 1.

In [38]:
df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/auto-mpg.csv")
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model-year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[398 rows x 7 columns]

In [39]:
df.columns = df.columns.str.capitalize()
df.columns

Index(['Mpg', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
       'Acceleration', 'Model-year'],
      dtype='object')

In [40]:
sorted(df.columns)

['Acceleration',
 'Cylinders',
 'Displacement',
 'Horsepower',
 'Model-year',
 'Mpg',
 'Weight']

In [33]:
q = sorted(df.columns)
q

df.columns = q

df.columns

df

Acceleration  Cylinders  Displacement  Horsepower  Model-year   Mpg  \
0            18.0          8         307.0       130.0        3504  12.0   
1            15.0          8         350.0       165.0        3693  11.5   
2            18.0          8         318.0       150.0        3436  11.0   
3            16.0          8         304.0       150.0        3433  12.0   
4            17.0          8         302.0       140.0        3449  10.5   
..            ...        ...           ...         ...         ...   ...   
393          27.0          4         140.0        86.0        2790  15.6   
394          44.0          4          97.0        52.0        2130  24.6   
395          32.0          4         135.0        84.0        2295  11.6   
396          28.0          4         120.0        79.0        2625  18.6   
397          31.0          4         119.0        82.0        2720  19.4   

     Weight  
0        70  
1        70  
2        70  
3        70  
4        70  
..      ...  
393      82  
394      82  
395      82  
396      82  
397      82  

[398 rows x 7 columns]

In [34]:
df.columns

Index(['Acceleration', 'Cylinders', 'Displacement', 'Horsepower', 'Model-year',
       'Mpg', 'Weight'],
      dtype='object')

In [41]:
# 데이터 값들도 컬럼따라서 정렬하려면
df = df[['Acceleration',
 'Cylinders',
 'Displacement',
 'Horsepower',
 'Model-year',
 'Mpg',
 'Weight']] 

In [42]:
df

Acceleration  Cylinders  Displacement  Horsepower  Model-year   Mpg  \
0            12.0          8         307.0       130.0          70  18.0   
1            11.5          8         350.0       165.0          70  15.0   
2            11.0          8         318.0       150.0          70  18.0   
3            12.0          8         304.0       150.0          70  16.0   
4            10.5          8         302.0       140.0          70  17.0   
..            ...        ...           ...         ...         ...   ...   
393          15.6          4         140.0        86.0          82  27.0   
394          24.6          4          97.0        52.0          82  44.0   
395          11.6          4         135.0        84.0          82  32.0   
396          18.6          4         120.0        79.0          82  28.0   
397          19.4          4         119.0        82.0          82  31.0   

     Weight  
0      3504  
1      3693  
2      3436  
3      3433  
4      3449  
..      ...  
393    2790  
394    2130  
395    2295  
396    2625  
397    2720  

[398 rows x 7 columns]

In [29]:
df

[[['Acceleration',
   'Cylinders',
   'Displacement',
   'Horsepower',
   'Model-year',
   'Mpg',
   'Weight']]]

## 2.

## 3.

In [49]:
em = pd.read_csv("https://gist.githubusercontent.com/kevin336/acbb2271e66c10a5b73aacf82ca82784/raw/e38afe62e088394d61ed30884dd50a6826eee0a8/employees.csv")
em

EMPLOYEE_ID   FIRST_NAME    LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0           198       Donald     OConnell  DOCONNEL  650.507.9833  21-JUN-07   
1           199      Douglas        Grant    DGRANT  650.507.9844  13-JAN-08   
2           200     Jennifer       Whalen   JWHALEN  515.123.4444  17-SEP-03   
3           201      Michael    Hartstein  MHARTSTE  515.123.5555  17-FEB-04   
4           202          Pat          Fay      PFAY  603.123.6666  17-AUG-05   
5           203        Susan       Mavris   SMAVRIS  515.123.7777  07-JUN-02   
6           204      Hermann         Baer     HBAER  515.123.8888  07-JUN-02   
7           205      Shelley      Higgins  SHIGGINS  515.123.8080  07-JUN-02   
8           206      William        Gietz    WGIETZ  515.123.8181  07-JUN-02   
9           100       Steven         King     SKING  515.123.4567  17-JUN-03   
10          101        Neena      Kochhar  NKOCHHAR  515.123.4568  21-SEP-05   
11          102          Lex      De Haan   LDEHAAN  515.123.4569  13-JAN-01   
12          103    Alexander       Hunold   AHUNOLD  590.423.4567  03-JAN-06   
13          104        Bruce        Ernst    BERNST  590.423.4568  21-MAY-07   
14          105        David       Austin   DAUSTIN  590.423.4569  25-JUN-05   
15          106        Valli    Pataballa  VPATABAL  590.423.4560  05-FEB-06   
16          107        Diana      Lorentz  DLORENTZ  590.423.5567  07-FEB-07   
17          108        Nancy    Greenberg  NGREENBE  515.124.4569  17-AUG-02   
18          109       Daniel       Faviet   DFAVIET  515.124.4169  16-AUG-02   
19          110         John         Chen     JCHEN  515.124.4269  28-SEP-05   
20          111       Ismael      Sciarra  ISCIARRA  515.124.4369  30-SEP-05   
21          112  Jose Manuel        Urman   JMURMAN  515.124.4469  07-MAR-06   
22          113         Luis         Popp     LPOPP  515.124.4567  07-DEC-07   
23          114          Den     Raphaely  DRAPHEAL  515.127.4561  07-DEC-02   
24          115    Alexander         Khoo     AKHOO  515.127.4562  18-MAY-03   
25          116       Shelli        Baida    SBAIDA  515.127.4563  24-DEC-05   
26          117        Sigal       Tobias   STOBIAS  515.127.4564  24-JUL-05   
27          118          Guy       Himuro   GHIMURO  515.127.4565  15-NOV-06   
28          119        Karen   Colmenares  KCOLMENA  515.127.4566  10-AUG-07   
29          120      Matthew        Weiss    MWEISS  650.123.1234  18-JUL-04   
30          121         Adam        Fripp    AFRIPP  650.123.2234  10-APR-05   
31          122        Payam     Kaufling  PKAUFLIN  650.123.3234  01-MAY-03   
32          123       Shanta      Vollman  SVOLLMAN  650.123.4234  10-OCT-05   
33          124        Kevin      Mourgos  KMOURGOS  650.123.5234  16-NOV-07   
34          125        Julia        Nayer    JNAYER  650.124.1214  16-JUL-05   
35          126        Irene  Mikkilineni  IMIKKILI  650.124.1224  28-SEP-06   
36          127        James       Landry   JLANDRY  650.124.1334  14-JAN-07   
37          128       Steven       Markle   SMARKLE  650.124.1434  08-MAR-08   
38          129        Laura       Bissot   LBISSOT  650.124.5234  20-AUG-05   
39          130        Mozhe     Atkinson  MATKINSO  650.124.6234  30-OCT-05   
40          131        James       Marlow   JAMRLOW  650.124.7234  16-FEB-05   
41          132           TJ        Olson   TJOLSON  650.124.8234  10-APR-07   
42          133        Jason       Mallin   JMALLIN  650.127.1934  14-JUN-04   
43          134      Michael       Rogers   MROGERS  650.127.1834  26-AUG-06   
44          135           Ki          Gee      KGEE  650.127.1734  12-DEC-07   
45          136        Hazel   Philtanker  HPHILTAN  650.127.1634  06-FEB-08   
46          137       Renske       Ladwig   RLADWIG  650.121.1234  14-JUL-03   
47          138      Stephen       Stiles   SSTILES  650.121.2034  26-OCT-05   
48          139         John          Seo      JSEO  650.121.2019  12-FEB-06   
49  

### 3-1. 사원번호가(EMPLOYEE_ID)가 200 이상이고 월급(SALARY이 5000 이 넘는 사람 수는?

In [50]:
em[(em.EMPLOYEE_ID>=200)&(em.SALARY>5000)]

EMPLOYEE_ID FIRST_NAME  LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
3          201    Michael  Hartstein  MHARTSTE  515.123.5555  17-FEB-04   
4          202        Pat        Fay      PFAY  603.123.6666  17-AUG-05   
5          203      Susan     Mavris   SMAVRIS  515.123.7777  07-JUN-02   
6          204    Hermann       Baer     HBAER  515.123.8888  07-JUN-02   
7          205    Shelley    Higgins  SHIGGINS  515.123.8080  07-JUN-02   
8          206    William      Gietz    WGIETZ  515.123.8181  07-JUN-02   

       JOB_ID  SALARY COMMISSION_PCT MANAGER_ID  DEPARTMENT_ID  
3      MK_MAN   13000             -         100             20  
4      MK_REP    6000             -         201             20  
5      HR_REP    6500             -         101             40  
6      PR_REP   10000             -         101             70  
7      AC_MGR   12008             -         101            110  
8  AC_ACCOUNT    8300             -         205            110

In [51]:
len(em[(em.EMPLOYEE_ID>=200)&(em.SALARY>5000)])

6

## 4. np로 1부터 20까지의 배열을 구하세요

In [55]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### 4-1. 위 코드의 누적합을 구하세요

In [56]:
np.cumsum(a)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210])

### 4-2. 1부터 100까지의 수 중 랜덤으로 10개의 수를 뽑은 배열을 2개 만들고, 배열을 비교하여 각 위치에서의 큰 수를 구하세요

In [68]:
a = np.random.randint(1,101,10)
b = np.random.randint(1,101,10)
print(a)
print(b)

np.maximum(a,b)

[27 30 40 37 30 55 22 16 83  5]
[ 53  49 100  45  75  80  58  53  60 100]


array([ 53,  49, 100,  45,  75,  80,  58,  53,  83, 100])

## 5. 

In [72]:
titanic=pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')
titanic 

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [73]:
### 5-1. ticket 컬럼에서 P 로 시작하는 행만 추출하세요

In [81]:
titanic['Ticket'].str.contains("^P.+")

0      False
1       True
2      False
3      False
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Ticket, Length: 891, dtype: bool

In [82]:
titanic['Ticket'].str.contains("^P.+").sum()

65

In [83]:
### 5-2. 이름 중에서 Mrs. 이 들어있는 사람들을 찾으세요

In [87]:
titanic["Name"].str.contains("Mrs+[.]")
# titanic["Name"].str.contains(".+\sMrs[.].+")

0      False
1       True
2      False
3       True
4      False
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

In [89]:
titanic["Name"].str.contains("Mrs+[.]").sum()

125

In [90]:
titanic[titanic["Name"].str.contains("Mrs+[.]")]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
8              9         1       3   
9             10         1       2   
15            16         1       2   
..           ...       ...     ...   
871          872         1       1   
874          875         1       2   
879          880         1       1   
880          881         1       2   
885          886         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
..                                                 ...     ...   ...    ...   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
874              Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0      1   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   

     Parch     Ticket     Fare Cabin Embarked  
1        0   PC 17599  71.2833   C85        C  
3        0     113803  53.1000  C123        S  
8        2     347742  11.1333   NaN        S  
9        0     237736  30.0708   NaN        C  
15       0     248706  16.0000   NaN        S  
..     ...        ...      ...   ...      ...  
871      1      11751  52.5542   D35        S  
874      0  P/PP 3381  24.0000   NaN        C  
879      1      11767  83.1583   C50        C  
880      1     230433  26.0000   NaN        S  
885      5     382652  29.1250   NaN        Q  

[125 rows x 12 columns]

In [91]:
### 5-3. Survived 컬럼 이름을 '생존' 으로 바꾸세요

In [100]:
titanic.rename(columns={"Survived" : "생존"},inplace=True)

In [102]:
titanic

PassengerId  생존  Pclass  \
0              1   0       3   
1              2   1       1   
2              3   1       3   
3              4   1       1   
4              5   0       3   
..           ...  ..     ...   
886          887   0       2   
887          888   1       1   
888          889   0       3   
889          890   1       1   
890          891   0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

## 6. 반 학생 25명의 수학 시험 데이터를 만드세요
평균 : 70, 표준편차 : 8

In [112]:
math = np.random.randn(25)*8 + 70
math

array([58.84300988, 76.0381593 , 66.23887664, 68.51469078, 71.0557594 ,
       81.53156812, 73.14075778, 65.95239369, 61.73711768, 71.67691521,
       70.46732117, 70.89295648, 81.94597289, 63.96610708, 62.67394103,
       72.70365071, 58.45590808, 62.78995884, 63.43728665, 71.53203955,
       83.90978773, 75.12758408, 59.96655946, 77.08812849, 62.20587152])

In [107]:
np.random.normal(70,8,size =25)

array([70.29754443, 71.10735509, 64.4983802 , 75.83428342, 56.74834969,
       77.88301812, 75.975278  , 76.41775588, 76.16676026, 63.34660667,
       69.32815876, 63.49593531, 68.30413245, 60.95255632, 82.50376732,
       73.09298388, 69.09123888, 68.27020572, 73.13438583, 72.42476034,
       73.0546023 , 68.49423877, 71.24370081, 64.2966562 , 59.42066246])

### 6-1. 55점 이하인 학생들의 수를 구하세요

In [118]:
math<=55

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [121]:
len(math[math <= 55])

0

In [115]:
sum(math <= 55)

0

In [117]:
(math<=55).sum()

0

### 6-2. 소수점 이하 두 자리만 표현

In [123]:
math.round(2)

array([58.84, 76.04, 66.24, 68.51, 71.06, 81.53, 73.14, 65.95, 61.74,
       71.68, 70.47, 70.89, 81.95, 63.97, 62.67, 72.7 , 58.46, 62.79,
       63.44, 71.53, 83.91, 75.13, 59.97, 77.09, 62.21])

## 7. 양궁 10번 을 쏜 점수를 구하세요

In [131]:
np.random.RandomState(1234)
arrow = np.random.randint(8,11,size=(2,10))

In [138]:
arrow

array([[ 9, 10, 10, 10,  8,  9,  9, 10, 10,  9],
       [10, 10, 10,  8, 10, 10,  9,  9, 10,  8]])

### 7-1. 점수의 누적합을 구하세요

In [144]:
arrow.cumsum(axis=1)

array([[ 9, 19, 29, 39, 47, 56, 65, 75, 85, 94],
       [10, 20, 30, 38, 48, 58, 67, 76, 86, 94]])

# 2교시

### 7-2. '총점' 컬럼을 추가해서 데이터프레임을 만들어주세요

In [182]:
df = pd.DataFrame(arrow,index=('A','B'),columns=range(1,11))

df

1   2   3   4   5   6   7   8   9   10
A   9  10  10  10   8   9   9  10  10   9
B  10  10  10   8  10  10   9   9  10   8

In [181]:
df["총점"]=arrow.sum(axis=1)

df

1   2   3   4   5   6  7   8   9  10  총점
A   9  10  10  10   8   9  9  10  10   9  94
B  10  10  10   8  10  10  9   9  10   8  94

In [184]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [185]:
np.exp(x)

array([ 2.71828183,  7.3890561 , 20.08553692])

# 3교시 : 184p~

In [191]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000} 
sdata

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [188]:
sdata = {'Ohio': [35000,1], 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000} 
sdata

{'Ohio': [35000, 1], 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [189]:
pd.DataFrame(sdata)

Ohio  Texas  Oregon  Utah
0  35000  71000   16000  5000
1      1  71000   16000  5000

In [192]:
pd.Series(sdata)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [194]:
'Ohio' in sdata

True

In [195]:
s = pd.Series(sdata)
s

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [196]:
s["Ohio"]

35000

In [197]:
pd.Series(sdata)
pd.Series(sdata, index = ["Ohio","Texas"])

Ohio     35000
Texas    71000
dtype: int64

In [198]:
pd.Series(sdata, index = ["California","Ohio","Texas"])

California        NaN
Ohio          35000.0
Texas         71000.0
dtype: float64

In [199]:
pd.isnull(s)

Ohio      False
Texas     False
Oregon    False
Utah      False
dtype: bool

In [203]:
pd.notnull(s)

Ohio      True
Texas     True
Oregon    True
Utah      True
dtype: bool

In [204]:
states = ["California","Ohio","Oregon","Texas"]

In [219]:
obj4 = pd.Series(sdata, index = states)

In [220]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [208]:
s

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [221]:
s + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [222]:
obj4.name = "population"

In [223]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [224]:
obj4.index

Index(['California', 'Ohio', 'Oregon', 'Texas'], dtype='object')

In [225]:
obj4.index.name = 'state'

In [226]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [227]:
obj4.index = ['California', 'ohio', 'Oregon', 'Texas']

In [228]:
obj4

California        NaN
ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

## 시리즈 만들기

### 1. 값이 2,4,6,8 로 만들기

In [230]:
s = pd.Series([2,4,6,8])

In [231]:
s

0    2
1    4
2    6
3    8
dtype: int64

### 2. index 추가하기
'a','b','c','d'

In [233]:
s.index = ['a','b','c','d']

In [234]:
s

a    2
b    4
c    6
d    8
dtype: int64

### 3. 딕셔너리를 써서 s를 다시 만들기

In [236]:
s = pd.Series({'a':2,'b':4,'c':6,'d':8})

In [237]:
s

a    2
b    4
c    6
d    8
dtype: int64

### 4. index가 'c' 인 값을 뽑으세요

In [244]:
s['c']

6

## 데이터프레임 188p~

In [247]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} 


In [248]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [249]:
frame = pd.DataFrame(data)

In [250]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [251]:
frame = pd.DataFrame(data, columns=['year','state','pop','dept'],index=['one','two','three','four','five','six'])

In [252]:
frame

year   state  pop dept
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [253]:
frame.columns

Index(['year', 'state', 'pop', 'dept'], dtype='object')

In [255]:
frame[['state','pop']]

state  pop
one      Ohio  1.5
two      Ohio  1.7
three    Ohio  3.6
four   Nevada  2.4
five   Nevada  2.9
six    Nevada  3.2

In [257]:
# 컬럼을 1개만 볼 때 사용
frame.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [259]:
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [267]:
dup_labels.append(Index : mandoo)

SyntaxError: invalid syntax (450159492.py, line 1)

# 5교시

In [277]:
s = pd.Series([2,4,6,8])
s 

0    2
1    4
2    6
3    8
dtype: int64

In [278]:
s.value_counts()

2    1
4    1
6    1
8    1
dtype: int64

In [279]:
s.index = ['a','b','c','d']
s

a    2
b    4
c    6
d    8
dtype: int64

In [281]:
s['e']=2

In [282]:
s

a    2
b    4
c    6
d    8
e    2
dtype: int64

In [283]:
s.values

array([2, 4, 6, 8, 2], dtype=int64)

In [292]:
s.astype('str') # 각각의 원소를 다루지 못한다는 단점이 있음

a    2
b    4
c    6
d    8
e    2
dtype: object

In [286]:
map(str,s)

In [288]:
list(map(str,s))

['2', '4', '6', '8', '2']

In [289]:
s

a    2
b    4
c    6
d    8
e    2
dtype: int64

In [291]:
list(map(str,s*10))

['20', '40', '60', '80', '20']

In [293]:
list(map(lambda x: x*10, s))

[20, 40, 60, 80, 20]

In [294]:
s.info()

<class 'pandas.core.series.Series'>
Index: 5 entries, a to e
Series name: None
Non-Null Count  Dtype
--------------  -----
5 non-null      int64
dtypes: int64(1)
memory usage: 252.0+ bytes


In [297]:
s.isin([2]) # 대괄호로 묶어서 리스트형식으로 줘야됨

a     True
b    False
c    False
d    False
e     True
dtype: bool

In [298]:
s.isin([2,4])

a     True
b     True
c    False
d    False
e     True
dtype: bool

In [299]:
frame

year   state  pop dept
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [307]:
frame.isin(["Ohio"]) # 차집합을 구할 때 'isin' 을 많이 씀

year  state    pop   dept
one    False   True  False  False
two    False   True  False  False
three  False   True  False  False
four   False  False  False  False
five   False  False  False  False
six    False  False  False  False

## 'Ohio' 가 들어있는 데이터프레임 검색(추출)

In [302]:
frame[frame["state"].isin(["Ohio"])] 

year state  pop dept
one    2000  Ohio  1.5  NaN
two    2001  Ohio  1.7  NaN
three  2002  Ohio  3.6  NaN

In [303]:
frame[frame['state']=='Ohio'] 

year state  pop dept
one    2000  Ohio  1.5  NaN
two    2001  Ohio  1.7  NaN
three  2002  Ohio  3.6  NaN

In [305]:
frame[(frame['state']=='Ohio')|(frame['state']=='Nevada')] 

year   state  pop dept
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [306]:
frame[frame["state"].isin(["Ohio","Nevada"])] 

year   state  pop dept
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [309]:
frame['dept'] = range(6)
frame

year   state  pop  dept
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

## 컬럼 삭제

In [312]:
frame.drop('dept',axis=1)

year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9
six    2003  Nevada  3.2

In [313]:
frame.iloc[:,:3]

year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9
six    2003  Nevada  3.2

In [316]:
del frame['dept'] # 아웃풋이 없다 => 바로 저장된다

KeyError: 'dept'

In [317]:
frame

year   state  pop
one    2000    Ohio  1.5
two    2001    Ohio  1.7
three  2002    Ohio  3.6
four   2001  Nevada  2.4
five   2002  Nevada  2.9
six    2003  Nevada  3.2

In [319]:
frame['state'] == 'Ohio'

one       True
two       True
three     True
four     False
five     False
six      False
Name: state, dtype: bool

In [320]:
frame['eastern'] = frame['state']=='Ohio'

In [321]:
frame

year   state  pop  eastern
one    2000    Ohio  1.5     True
two    2001    Ohio  1.7     True
three  2002    Ohio  3.6     True
four   2001  Nevada  2.4    False
five   2002  Nevada  2.9    False
six    2003  Nevada  3.2    False

In [322]:
frame['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [326]:
frame['eastern'] = np.where(frame['state']=="Ohio","yes","no")

In [327]:
frame

year   state  pop eastern
one    2000    Ohio  1.5     yes
two    2001    Ohio  1.7     yes
three  2002    Ohio  3.6     yes
four   2001  Nevada  2.4      no
five   2002  Nevada  2.9      no
six    2003  Nevada  3.2      no

In [328]:
pop = {"Nevada":{2001: 2.4, 2002: 2.9}, 'Ohio':{2000:1.5, 2001: 1.7,2002:3.6}}

In [329]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [330]:
pd.DataFrame(pop)

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [331]:
pd.DataFrame(pop).T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [332]:
pd.DataFrame(pop, index = [2001, 2002])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6

In [333]:
frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [334]:
frame3.index.name = '년도'
frame3.columns.name = '주'
frame3

주     Nevada  Ohio
년도                
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

# 6교시 : 색인 객체 195p~

In [335]:
obj = pd.Series(range(3), index = ['a','b','c'])
obj

a    0
b    1
c    2
dtype: int64

In [336]:
obj.index

Index(['a', 'b', 'c'], dtype='object')

In [337]:
obj.index[1]

'b'

In [338]:
obj.index[:2]

Index(['a', 'b'], dtype='object')

In [340]:
obj.index[1] = "B" # 색인 객체는 변경 불가

TypeError: Index does not support mutable operations

In [341]:
obj

a    0
b    1
c    2
dtype: int64

In [342]:
'a' in obj.index

True

In [344]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='주')

In [346]:
"Ohio" in frame3.columns

True

In [348]:
obj['d'] = 10
obj

a     0
b     1
c     2
d    10
dtype: int64

In [349]:
obj.index = ['a','b','c','a']

In [350]:
obj

a     0
b     1
c     2
a    10
dtype: int64

In [352]:
obj['a'] # pandas 의 인덱스는 중복 값 허용

a     0
a    10
dtype: int64

In [353]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index = ['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [354]:
new_index = ['a','b','c','d']
obj.reindex(new_index)

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

In [355]:
new_index = ['b','c','d','e']
obj.reindex(new_index)

b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [356]:
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])

In [357]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [358]:
obj3.reindex(range(6))

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [359]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [360]:
obj3.reindex(range(6), method='bfill')

0      blue
1    purple
2    purple
3    yellow
4    yellow
5       NaN
dtype: object

In [361]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [363]:
obj = obj.reindex(["a",'b','c','d'])
obj

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

In [364]:
obj

a   -5.3
b    7.2
c    3.6
d    4.5
dtype: float64

In [365]:
obj[2:]

c    3.6
d    4.5
dtype: float64

In [366]:
obj[:3]=3

In [367]:
obj

a    3.0
b    3.0
c    3.0
d    4.5
dtype: float64

In [368]:
df

1   2   3   4   5   6   7   8   9   10
A   9  10  10  10   8   9   9  10  10   9
B  10  10  10   8  10  10   9   9  10   8

In [370]:
df = pd.DataFrame(np.arange(1,17).reshape(4,4))
df

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [371]:
## 6보다 작거나 같은 수는 0으로 바꾸기

In [372]:
# np.where([df<=6],0,df)
df[df<=6]=0

In [373]:
df

0   1   2   3
0   0   0   0   0
1   0   0   7   8
2   9  10  11  12
3  13  14  15  16

In [374]:
df.iloc[2, : ]

0     9
1    10
2    11
3    12
Name: 2, dtype: int32

# 7교시

In [378]:
data = pd.DataFrame(np.arange(16).reshape(4,4),index=['Ohio','Colorado','Utah','New York'],columns=['one','two','three','four'])

In [379]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### 데이터프레임에서 열(컬럼)을 불러올 때
```
-> 1. 000['컬럼 이름'] # 컬럼 1개만 불러올 때
-> 2. 000[['컬럼이름1', '컬럼이름2']] # 컬럼 2개 이상 불러올 때
```

In [408]:
data.columns

Index(['one', 'two', 'three', 'four'], dtype='object')

In [392]:
data[['one','three']]

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [398]:
data['four']

Ohio         3
Colorado     7
Utah        11
New York    15
Name: four, dtype: int32

### 데이터프레임에서 행(로우)을 불러올 때
```
-> 1. 슬라이싱
-> 2. 000.loc['로우 이름']
-> 3. 000.iloc[로우 인덱스 번호]
-> 4. 000[000['컬럼 이름'] > 숫자] # 불리언 배열로 불러오기
000['컬럼이름'] > 숫자 -> 불리언 값으로 리턴
```

In [395]:
data.iloc[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [397]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [412]:
data['one']>5

Ohio        False
Colorado    False
Utah         True
New York     True
Name: one, dtype: bool

In [411]:
data[data['one']>5]

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

# 8교시

In [491]:


import matplotlib.pyplot as plt
# pyplot은 시퀀스 스칼라를 지원
# 시퀀스 스칼라 : 순서가 있는 숫자 -> list 또는 Series 종류

plt.title("exponential graph")

x = np.arange(1,6)

y1 = np.exp(x) # e의 1승, e의 2승, e의 3승 ~ e의 5승

y2 = 2**x

y3 = 3**x




plt.plot(x,y1,label='e^x')
plt.plot(x,y2,label='2^x')
plt.plot(x,y3,label='3^x')
plt.legend()
plt.show()

In [498]:
data = {'금': [40, 40, 30, 20, 20, 10],
        '은': [30, 20, 20, 16, 14, 14],
        '동': [10, 10, 20, 15, 10, 10]} 
data

{'금': [40, 40, 30, 20, 20, 10],
 '은': [30, 20, 20, 16, 14, 14],
 '동': [10, 10, 20, 15, 10, 10]}

In [513]:
frame = pd.DataFrame(data,index=range(1,7))
frame

금   은   동
1  40  30  10
2  40  20  10
3  30  20  20
4  20  16  15
5  20  14  10
6  10  14  10

In [ ]:
obj4.index = ['California', 'ohio', 'Oregon', 'Texas']

In [511]:
frame.index = ['1','2','3','4','5','6']