# pandas

## 시리즈

### 만들기


In [5]:
import pandas as pd

In [6]:
animals = ["Tiger","Bear","Cat"]
animals

['Tiger', 'Bear', 'Cat']

In [12]:
s = pd.Series(animals)
s
# pandas에서 말하는 object = string = charactor

0    Tiger
1     Bear
2      Cat
dtype: object

In [13]:
type(s)

pandas.core.series.Series

In [14]:
s.index.name

# 5교시

## 딕셔너리 -> 시리즈

In [20]:
di = {'a':1,'b':2,'c':3}
di

{'a': 1, 'b': 2, 'c': 3}

In [24]:
di_1 = pd.Series(di)
s = di_1
s

a    1
b    2
c    3
dtype: int64

In [26]:
s['a'] # 문자열로 인덱스 접근가능

1

## 데이터프레임

In [27]:
import numpy as np

In [30]:
df = pd.DataFrame(np.arange(6).reshape(2,3))
df

0  1  2
0  0  1  2
1  3  4  5

In [31]:
type(df)

pandas.core.frame.DataFrame

In [32]:
pd.DataFrame({'a':1,'b':2,'c':3})

ValueError: If using all scalar values, you must pass an index

In [34]:
pd.DataFrame({'a':[1,2],'b':2,'c':3})
# 키 : 칼럼의 이름, 밸류 : 로우

a  b  c
0  1  2  3
1  2  2  3

In [39]:
pd.DataFrame([4,5,6,7],index=['A','B','C','D'])

0
A  4
B  5
C  6
D  7

In [235]:
x = pd.DataFrame(np.arange(1,17).reshape(4,4))
x

0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16

In [241]:
x = pd.DataFrame(np.arange(1,17).reshape(4,4),index=['가','나','다','라'],columns=['갑','을','병','정'])
x

갑   을   병   정
가   1   2   3   4
나   5   6   7   8
다   9  10  11  12
라  13  14  15  16

In [203]:
z= pd.DataFrame(np.arange(16).reshape(4,4),index=['A','B','C','D'])
print(z)
sum(np.diagonal(z))

    0   1   2   3
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15


30

In [204]:
z.drop("A")

0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15

In [206]:
z.drop(0,axis=1)

1   2   3
A   1   2   3
B   5   6   7
C   9  10  11
D  13  14  15

In [74]:
df = pd.DataFrame([[15, '남','남중'],[17,'여','여중']],index = ['철수','영희'],columns=['나이','성별','학교'])
df

나이 성별  학교
철수  15  남  남중
영희  17  여  여중

In [48]:
df.index

Index(['철수', '영희'], dtype='object')

In [49]:
df.columns

Index(['나이', '성별', '학교'], dtype='object')

## 행과 열 다루기

### 삭제

In [53]:
# 행삭제
df.drop('철수')

나이 성별  학교
영희  17  여  여중

In [60]:
df

나이 성별  학교
영희  17  여  여중

In [73]:
# 1번
d = df.drop('철수')
d

나이 성별  학교
영희  17  여  여중

In [66]:
# 2번
df.drop('철수',inplace=True)

In [61]:
df

나이 성별  학교
영희  17  여  여중

In [75]:
# 3번
df.iloc[[1], :]

나이 성별  학교
영희  17  여  여중

In [244]:
x.iloc[1:,1:] # x에 저장 안되어 있음

을   병   정
나   6   7   8
다  10  11  12
라  14  15  16

In [243]:
x

갑   을   병   정
가   1   2   3   4
나   5   6   7   8
다   9  10  11  12
라  13  14  15  16

In [239]:
sum(np.diagonal(x.iloc[1:,1:]))

33

In [240]:
type(x.iloc[1:,1:])

pandas.core.frame.DataFrame

In [217]:
z.iloc[[1,2,3],[1,2,3]]

1   2   3
B   5   6   7
C   9  10  11
D  13  14  15

In [225]:
z.iloc[1:,1:]

1   2   3
B   5   6   7
C   9  10  11
D  13  14  15

In [229]:
sum(np.diagonal(z))

30

In [231]:
sum(np.diagonal(z.iloc[1:,1:]))

30

In [227]:
z

0   1   2   3
A   0   1   2   3
B   4   5   6   7
C   8   9  10  11
D  12  13  14  15

In [80]:
df = pd.DataFrame([[15, '남','남중'],[17,'여','여중']],index = ['철수','영희'],columns=['나이','성별','학교'])
df

나이 성별  학교
철수  15  남  남중
영희  17  여  여중

In [77]:
df.drop(['철수','영희'])

Empty DataFrame
Columns: [나이, 성별, 학교]
Index: []

In [79]:
df.drop("철수",axis=0)

나이 성별  학교
영희  17  여  여중

### 열삭제
-> 객체.drop(열이름, axis=1)

In [81]:
df.drop(['나이','성별'],axis=1)

학교
철수  남중
영희  여중

In [91]:
df = pd.DataFrame([[90,98,85,100],[80,89,95,90],[70,95,100,90]],index=["서준","우현","인아"],columns=["수학","영어","음악","체육"])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [92]:
df = pd.DataFrame({'수학': [90, 80, 70], '영어' : [98,89, 95], 
                  '음악':[85, 95, 100], '체육' : [100, 90, 90]},index=["서준","우현","인아"]) 
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

## 행선택

In [95]:
a = df.values
a

array([[ 90,  98,  85, 100],
       [ 80,  89,  95,  90],
       [ 70,  95, 100,  90]], dtype=int64)

In [96]:
a[0,0]

90

In [99]:
a[1,:]
# a[1]

array([80, 89, 95, 90], dtype=int64)

In [100]:
a[:,1]

array([98, 89, 95], dtype=int64)

In [101]:
df.iloc[1,:]

수학    80
영어    89
음악    95
체육    90
Name: 우현, dtype: int64

In [103]:
# df 은 array가 아니다!!!
df.iloc[:,1]

서준    98
우현    89
인아    95
Name: 영어, dtype: int64

# 6교시

In [104]:
df.iloc[0,:] # integer location

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [105]:
df.loc["서준",:] # location

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [106]:
df.loc[["서준","우현"],:]

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [107]:
df.iloc[[0,1],:]

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [109]:
type(df.loc['서준',:])

pandas.core.series.Series

In [110]:
type(df.loc[['서준'],:])

pandas.core.frame.DataFrame

In [111]:
df.loc[['서준'],:]

수학  영어  음악   체육
서준  90  98  85  100

### 퀴즈

In [112]:
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [114]:
# 1. 수학, 영어 칼럼뽑기
df.loc[:,["수학","영어"]]

수학  영어
서준  90  98
우현  80  89
인아  70  95

In [115]:
# 2. 수학칼럼만 데이터프레임으로 뽑기
df.loc[:,["수학"]]

수학
서준  90
우현  80
인아  70

In [118]:
df.loc['서준'] # 행 : 됨

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [119]:
df.loc['수학'] # 열 : 안됨

KeyError: '수학'

In [122]:
df.iloc[[1]]

수학  영어  음악  체육
우현  80  89  95  90

In [123]:
df['수학']

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [125]:
df.수학

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [127]:
df.loc['서준'] # 행
df['수학'] , df.수학 # 열

(서준    90
 우현    80
 인아    70
 Name: 수학, dtype: int64,
 서준    90
 우현    80
 인아    70
 Name: 수학, dtype: int64)

In [124]:
# 위에 코드들 처럼 헷갈리니까 loc, iloc 쓰고 접근할 것

## 열선택

```
df['수학']
df[['음악','체육']]
df.수학
```

## 이름바꾸기

In [131]:
df.index

Index(['서준', '우현', '인아'], dtype='object')

In [137]:
df.index = ["박서준","남우현","설인아"]

In [138]:
df.index

Index(['박서준', '남우현', '설인아'], dtype='object')

In [139]:
df.index[1]

'남우현'

In [140]:
df.index[1] = "우현"

TypeError: Index does not support mutable operations

In [143]:
df.columns

Index(['수학', '영어', '음악', '체육'], dtype='object')

In [147]:
df.columns = ['수학', '영어', '음악', 'PE']
df

수학  영어   음악   PE
박서준  90  98   85  100
남우현  80  89   95   90
설인아  70  95  100   90

In [150]:
# 컬럼 1개만 바꾸기
df.rename(columns={"체육":"PE"})

수학  영어   음악   PE
박서준  90  98   85  100
남우현  80  89   95   90
설인아  70  95  100   90

In [154]:
df.rename({"PE":"체육"},axis=1, inplace=True)
df

수학  영어   음악   체육
박서준  90  98   85  100
남우현  80  89   95   90
설인아  70  95  100   90

### 연습

In [196]:
import plotly.express as px
df = px.data.gapminder()
# df.head()
# df.shape
df

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0     Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1     Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2     Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3     Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4     Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   
...           ...       ...   ...      ...       ...         ...       ...   
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306       ZWE   
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786       ZWE   
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960       ZWE   
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623       ZWE   
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
0           4  
1           4  
2           4  
3           4  
4           4  
...       ...  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716  

[1704 rows x 8 columns]

In [159]:
df.shape 

(1704, 8)

In [160]:
df.head()

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2  Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3  Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4  Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   

   iso_num  
0        4  
1        4  
2        4  
3        4  
4        4

In [163]:
df.iloc[:10,:5]

country continent  year  lifeExp       pop
0  Afghanistan      Asia  1952   28.801   8425333
1  Afghanistan      Asia  1957   30.332   9240934
2  Afghanistan      Asia  1962   31.997  10267083
3  Afghanistan      Asia  1967   34.020  11537966
4  Afghanistan      Asia  1972   36.088  13079460
5  Afghanistan      Asia  1977   38.438  14880372
6  Afghanistan      Asia  1982   39.854  12881816
7  Afghanistan      Asia  1987   40.822  13867957
8  Afghanistan      Asia  1992   41.674  16317921
9  Afghanistan      Asia  1997   41.763  22227415

In [164]:
df[:10]

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0  Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1  Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2  Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3  Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4  Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   
5  Afghanistan      Asia  1977   38.438  14880372  786.113360       AFG   
6  Afghanistan      Asia  1982   39.854  12881816  978.011439       AFG   
7  Afghanistan      Asia  1987   40.822  13867957  852.395945       AFG   
8  Afghanistan      Asia  1992   41.674  16317921  649.341395       AFG   
9  Afghanistan      Asia  1997   41.763  22227415  635.341351       AFG   

   iso_num  
0        4  
1        4  
2        4  
3        4  
4        4  
5        4  
6        4  
7        4  
8        4  
9        4

In [166]:
df[-10:]

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
1694  Zimbabwe    Africa  1962   52.358   4277736  527.272182       ZWE   
1695  Zimbabwe    Africa  1967   53.995   4995432  569.795071       ZWE   
1696  Zimbabwe    Africa  1972   55.635   5861135  799.362176       ZWE   
1697  Zimbabwe    Africa  1977   57.674   6642107  685.587682       ZWE   
1698  Zimbabwe    Africa  1982   60.363   7636524  788.855041       ZWE   
1699  Zimbabwe    Africa  1987   62.351   9216418  706.157306       ZWE   
1700  Zimbabwe    Africa  1992   60.377  10704340  693.420786       ZWE   
1701  Zimbabwe    Africa  1997   46.809  11404948  792.449960       ZWE   
1702  Zimbabwe    Africa  2002   39.989  11926563  672.038623       ZWE   
1703  Zimbabwe    Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
1694      716  
1695      716  
1696      716  
1697      716  
1698      716  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716

In [187]:
# df에서 행추출
df = df[100:600:100]
df

country continent  year  lifeExp       pop     gdpPercap  \
100      Bangladesh      Asia  1972   45.252  70759295    630.233627   
200    Burkina Faso    Africa  1992   50.260   8878303    931.752773   
300        Colombia  Americas  1952   50.643  12350771   2144.115096   
400  Czech Republic    Europe  1972   70.290   9862158  13108.453600   
500         Eritrea    Africa  1992   49.991   3668440    582.858510   

    iso_alpha  iso_num  
100       BGD       50  
200       BFA      854  
300       COL      170  
400       CZE      203  
500       ERI      232

In [175]:
# df에서 열삭제

In [178]:
# 방법 1
df = df.iloc[:,:5]
df

country continent  year  lifeExp       pop
100      Bangladesh      Asia  1972   45.252  70759295
200    Burkina Faso    Africa  1992   50.260   8878303
300        Colombia  Americas  1952   50.643  12350771
400  Czech Republic    Europe  1972   70.290   9862158
500         Eritrea    Africa  1992   49.991   3668440

In [193]:
df

country continent  year  lifeExp       pop   gdpPercap iso_alpha  \
0     Afghanistan      Asia  1952   28.801   8425333  779.445314       AFG   
1     Afghanistan      Asia  1957   30.332   9240934  820.853030       AFG   
2     Afghanistan      Asia  1962   31.997  10267083  853.100710       AFG   
3     Afghanistan      Asia  1967   34.020  11537966  836.197138       AFG   
4     Afghanistan      Asia  1972   36.088  13079460  739.981106       AFG   
...           ...       ...   ...      ...       ...         ...       ...   
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306       ZWE   
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786       ZWE   
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960       ZWE   
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623       ZWE   
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298       ZWE   

      iso_num  
0           4  
1           4  
2           4  
3           4  
4           4  
...       ...  
1699      716  
1700      716  
1701      716  
1702      716  
1703      716  

[1704 rows x 8 columns]